Update README.md
intel/scikit-learn-intelex pull request #1020
Opened 2022-07-20 23:59 UTC by bdmoore1

# Description
Added style guide to the README for those who contribute to documentation.

Changes proposed in this pull request:
- Styles section in README
-
-

2022-07-25 15:47 UTC, bdmoore1 commented
@PivovarA do you know why CI is failing?

2022-08-02 14:11 UTC, Alexsandruss commented
I guess CI fails might be ignored for docs only PRs.
@outoftardis, can you verify that change is meaningful and suitable for README.md (not another file like CONTRIBUTING.md, for example)?

2022-08-02 14:27 UTC, outoftardis commented
> I guess CI fails might be ignored for docs only PRs. @outoftardis, can you verify that change is meaningful and suitable for README.md (not another file like CONTRIBUTING.md, for example)?

You are right. CONTRIBUTING.md is a better place for this info

2022-08-04 09:26 UTC, Alexsandruss approved these changes

2022-08-04 13:18 UTC, Alexsandruss requested changes

2022-08-04 13:18 UTC, Alexsandruss commented on CONTRIBUTING.md
> +   ^^^^^^^^^
This block is automatically formatted in Markdown and will look confusing if one reads .md file not in raw mode, insert it as Markdown code block using:

\`\`\`
[RST formatting examples]
\`\`\`

2022-12-17 22:40 UTC, napetrov commented
Better version of contributing.md was intergrated

2022-12-17 22:40 UTC, closed without merging