ENH: multi-gpu enable
intel/scikit-learn-intelex pull request #1058
Opened 2022-11-04 01:11 UTC by samir-nasibli

# Description

TBD 

Please include a summary of the change. For large or complex changes please include enough information to introduce your change and explain motivation for it.

Changes proposed in this pull request:
-
-
-

2022-11-22 02:29 UTC, samir-nasibli commented
Waiting #1059 #1064 and https://github.com/oneapi-src/oneDAL/pull/2156

2023-02-07 17:05 UTC, napetrov commented on onedal/common/mpi_primitives.cpp
> +#endif
```suggestion
#endif

```

2023-02-07 17:59 UTC, Alexsandruss requested changes
Rebase on last changes in sklearnex.
This PR should pass github CI.

2023-03-24 20:25 UTC, samir-nasibli commented
Outdated. Implemented on #1214

2023-03-24 20:25 UTC, closed without merging