Rewrite _onedal_gpu_supported method for SVC
intel/scikit-learn-intelex pull request #1362
Opened 2023-07-13 23:36 UTC by olegkkruglov

Changes proposed in this pull request:
- Make _onedal_gpu_supported method for SVC shorter and more readable

2023-07-14 10:37 UTC, olegkkruglov commented
/intelci: run

2023-08-02 22:25 UTC, samir-nasibli commented
@olegkkruglov please resolve the conflict

2023-08-18 12:08 UTC, samir-nasibli commented
@please rebase your branches and run intelci

2023-08-18 12:09 UTC, samir-nasibli commented
@olegkkruglov please rebase your branches and run intelci

2023-08-19 17:46 UTC, olegkkruglov commented
/intelci: run

2023-08-25 15:47 UTC, samir-nasibli requested changes
Please rewrite it/ make a refactoring without changing the logic.

2023-08-25 15:47 UTC, samir-nasibli commented on sklearnex/svm/svc.py
> +                (hasattr(self, "_onedal_estimator"), "oneDAL model was not trained")
wrong logic for `conditions` list. Conditions for inference and for train stages are different, don't mix them

2023-08-29 10:59 UTC, Alexsandruss requested changes

2023-08-29 10:59 UTC, Alexsandruss commented on sklearnex/svm/svc.py
> -        raise RuntimeError(f"Unknown method {method_name} in {class_name}")
RuntimeError should exist at the end of function like in other estimators or this support checking workflow should be changed

2023-08-29 15:18 UTC, samir-nasibli commented
/intelci: run

2023-08-29 15:22 UTC, samir-nasibli commented
GPU CI Job: http://intel-ci.intel.com/ee467fd9-23b2-f12c-b9f3-a4bf010d0e2e. Specifically for sklearnex/daal4py tests/examples on GPU.

2023-08-30 07:54 UTC, merged