update github template and CONTRIBUTING.md
intel/scikit-learn-intelex pull request #1388
Opened 2023-08-02 10:26 UTC by samir-nasibli

# Description
I am proposing some changes on our github templates for PRs.
let's discuss unification of our PRs.
Please propose your suggestions for the each section.

Based on https://github.com/oneapi-src/oneTBB/blob/master/.github/pull_request_template.md

2023-08-02 11:00 UTC, Alexsandruss requested changes

2023-08-02 11:02 UTC, alexandraepan commented on .github/Pull_Request_template.md
> +_Add a comprehensive description of proposed changes_
we can delete this line

2023-08-02 12:11 UTC, samir-nasibli commented on CONTRIBUTING.md
> +API: an (incompatible) API change
This acronyms taken from https://numpy.org/doc/stable/dev/development_workflow.html#writing-the-commit-message.
This is for features/enhancements that brings API changes, that also could break compatibility.

We may discuss on the set of acronyms used for git messages.

2023-08-02 12:27 UTC, samir-nasibli commented
I suggest not to pile up the PRs template. I will collect your feedbacks and comments. I think a lot them can be transferred to [CONTRIBUTING.md](https://github.com/intel/scikit-learn-intelex/pull/1388/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055).
In the template itself, we can leave a link to CONTRIBUTING.md and leave the main checklists useful code owners and reviewers

2023-12-19 16:27 UTC, samir-nasibli commented
I will move PR template changes into separate topic.

2024-03-11 16:29 UTC, ethanglaser commented
Closing due to lack of recent activity - please re-open when progress continues

2024-03-12 12:04 UTC, samir-nasibli commented
@aepanchi @emmwalsh Please, take a look, and in case please close this PR.

2024-04-30 20:45 UTC, closed without merging