chore: migrate linting from GHA to Azure
intel/scikit-learn-intelex pull request #1391
Opened 2023-08-07 16:10 UTC by ahuber21

We're experiencing long queue times for the GH linting action. Move to Azure for mitigation

2023-08-07 16:18 UTC, ahuber21 commented
The CodeFactor failure is a `#TODO` comment in a formatted file which must be addressed separately.

2023-08-07 16:23 UTC, ahuber21 commented
/intelci: run

2023-08-07 21:13 UTC, samir-nasibli requested changes
Sorry, let's separate linting migration and code refactoring/style alignment.

2023-08-08 07:29 UTC, ahuber21 commented
/intelci: run

2023-08-08 07:41 UTC, ahuber21 commented
No problem @samir-nasibli, I've added a filter so that the CI targets only the files that we have already reformatted. If we decide to format the remaining files, the filter in `pyproject.toml` needs to be updated.

2023-08-08 09:13 UTC, Alexsandruss approved these changes

2023-08-08 12:04 UTC, samir-nasibli commented on pyproject.toml
> +include = "(examples|onedal|sklearnex)/.*py$"
We have py sources not only in these mentioned directories.

2023-08-08 12:06 UTC, samir-nasibli commented
I am ok with the rest of the changes, but I think enabling format check only for specific directories is not right. Let's avoid.

2023-08-08 13:01 UTC, ahuber21 commented
> I am ok with the rest of the changes, but I think enabling format check only for specific directories is not right. Let's avoid.

We cannot do both i) separate this migration and linting of files into two PRs (as you requested in your first comment), and ii) filter out files that weren't linted before.
Please make a suggestion of your preferred order of operations. I will provide the necessary changes.

2023-08-08 14:02 UTC, samir-nasibli approved these changes
We already discussed it. Let's do remaining formatting in separate branches and remove the filter then.

2023-08-08 14:25 UTC, merged