ENH: `sklearnex` verbose mode messenger
intel/scikit-learn-intelex pull request #1424
Opened 2023-08-31 15:37 UTC by samir-nasibli

# Description
**[WIP]**
`sklearnex` verbose mode messenger.
**currently will break preview testing**
fixes #1416 

# TODO:
* refactoring
* adding tests for this messenger
* update preview with new messenger:
  * currently it will break preview testing

2023-08-31 15:39 UTC, samir-nasibli commented on sklearnex/_device_offload.py
> +            else:
Logic will be carefully updated.

2023-08-31 15:43 UTC, samir-nasibli commented on sklearnex/_utils.py
> +            self.write_log(queue)
will be removed.

2023-09-04 13:21 UTC, KulikovNikita reviewed
In general looks fine to me

2023-09-04 23:12 UTC, samir-nasibli commented on sklearnex/preview/ensemble/extra_trees.py
> +            )
@icfaust please check it

2023-09-05 02:36 UTC, samir-nasibli commented
/intelci: run

2023-09-05 11:25 UTC, Alexsandruss requested changes

2023-09-05 11:25 UTC, Alexsandruss commented on sklearnex/_utils.py
> +    def get_status(self, queue=None):
`queue` is unused.
```suggestion
    def get_status(self):
```

2023-09-05 11:25 UTC, Alexsandruss commented on sklearnex/neighbors/lof.py
> +                f"sklearn.cluster.{class_name}.{method_name}"
```suggestion
                f"sklearn.neighbors.{class_name}.{method_name}"
```

2023-09-05 11:25 UTC, Alexsandruss commented on sklearnex/neighbors/lof.py
> +                f"sklearn.cluster.{class_name}.{method_name}"
```suggestion
                f"sklearn.neighbors.{class_name}.{method_name}"
```

2023-09-05 11:55 UTC, samir-nasibli commented on sklearnex/_utils.py
> +    def write_log(self, queue=None):
I think we should have different implementations. At least we have different flows there

2023-09-05 11:56 UTC, samir-nasibli commented on sklearnex/neighbors/lof.py
> +                f"sklearn.cluster.{class_name}.{method_name}"
Goof catch. thanks

2023-09-05 12:10 UTC, samir-nasibli commented on sklearnex/neighbors/lof.py
> +                f"sklearn.cluster.{class_name}.{method_name}"
fixed.

2023-09-05 12:11 UTC, samir-nasibli commented
/intelci: run

2023-09-05 13:31 UTC, Alexsandruss commented on sklearnex/_utils.py
> +    def write_log(self, queue=None):
No, branches of `get_patch_message` functions can be easily stacked and it's the only difference in implementations

2023-09-05 13:34 UTC, Alexsandruss submitted a review, later dismissed
Merge `get_patch_message` functions:
```python
def get_patch_message(s, queue=None):
    if s == "daal":
        message = "running accelerated version on "
        if oneapi_is_available:
            dev = _get_device_name_sycl_ctxt()
            if dev == "cpu" or dev is None:
                message += "CPU"
            elif dev == "gpu":
                message += "GPU"
            else:
                raise ValueError(
                    f"Unexpected device name {dev}." " Supported types are cpu and gpu"
                )
        else:
            message += "CPU"
    elif s == "onedal":
        message = "running accelerated version on "
        if queue is not None:
            if queue.sycl_device.is_gpu:
                message += "GPU"
            elif queue.sycl_device.is_cpu:
                message += "CPU"
            else:
                raise RuntimeError("Unsupported device")
        else:
            message += "CPU"
    elif s == "sklearn":
        message = "fallback to original Scikit-learn"
    elif s in ["sklearn_after_daal", "sklearn_after_daal"]:
        message = "failed to run accelerated version, fallback to original Scikit-learn"
    else:
        raise ValueError(
            f"Invalid input - expected one of 'daal', 'onedal', 'sklearn',"
            f" 'sklearn_after_daal', 'sklearn_after_onedal', got {s}"
        )
    return message
```

2023-09-05 13:40 UTC, samir-nasibli commented
> Merge `get_patch_message` functions:
> 
> ```python
> def get_patch_message(s, queue=None):
>     if s == "daal":
>         message = "running accelerated version on "
>         if oneapi_is_available:
>             dev = _get_device_name_sycl_ctxt()
>             if dev == "cpu" or dev is None:
>                 message += "CPU"
>             elif dev == "gpu":
>                 message += "GPU"
>             else:
>                 raise ValueError(
>                     f"Unexpected device name {dev}." " Supported types are cpu and gpu"
>                 )
>         else:
>             message += "CPU"
>     elif s == "onedal":
>         message = "running accelerated version on "
>         if queue is not None:
>             if queue.sycl_device.is_gpu:
>                 message += "GPU"
>             elif queue.sycl_device.is_cpu:
>                 message += "CPU"
>             else:
>                 raise RuntimeError("Unsupported device")
>         else:
>             message += "CPU"
>     elif s == "sklearn":
>         message = "fallback to original Scikit-learn"
>     elif s in ["sklearn_after_daal", "sklearn_after_daal"]:
>         message = "failed to run accelerated version, fallback to original Scikit-learn"
>     else:
>         raise ValueError(
>             f"Invalid input - expected one of 'daal', 'onedal', 'sklearn',"
>             f" 'sklearn_after_daal', 'sklearn_after_onedal', got {s}"
>         )
>     return message
> ```

That is bad practice. Daal4py shouldn\t know about sklearnex impl specifics.
Also skleearnex falls to the daal4py, that uses it is own logger.

2023-09-05 13:41 UTC, merged

2023-09-05 13:48 UTC, Alexsandruss commented
> > Merge `get_patch_message` functions:
> > ```python
> > def get_patch_message(s, queue=None):
> >     ...
> > ```
> 
> That is bad practice. Daal4py shouldn\t know about sklearnex impl specifics. Also skleearnex falls to the daal4py, that uses it is own logger.

Logger is common functionality of daal4py and sklearnex. Thus, it should be aware of both modules. The only problem it's stored in one of them instead of separate place

2023-09-05 14:18 UTC, samir-nasibli commented
> Logger is common functionality of daal4py and sklearnex. Thus, it should be aware of both modules. The only problem it's stored in one of them instead of separate place

Sure. Thank you for your thoughts.
We use different instances anyway and they are related, only the behavior of some methods is changed for onedal4py backed specifics.
daal4py doesn't need to know about the `sklearnex` implementation specifics.

2023-09-05 15:49 UTC, Alexsandruss commented
> > Logger is common functionality of daal4py and sklearnex. Thus, it should be aware of both modules. The only problem it's stored in one of them instead of separate place
> 
> Sure. Thank you for your thoughts. We use different instances anyway and they are related, only the behavior of some methods is changed for onedal4py backed specifics. daal4py doesn't need to know about the `sklearnex` implementation specifics.

We used *one instance* before this PR and there was no need for another. `daal4py` was not aware of `sklearnex` specifics, common logger was just stored in `daal4py` namespace.

2023-09-05 15:59 UTC, samir-nasibli commented
> > > Logger is common functionality of daal4py and sklearnex. Thus, it should be aware of both modules. The only problem it's stored in one of them instead of separate place
> > 
> > 
> > Sure. Thank you for your thoughts. We use different instances anyway and they are related, only the behavior of some methods is changed for onedal4py backed specifics. daal4py doesn't need to know about the `sklearnex` implementation specifics.
> 
> We used _one instance_ before this PR and there was no need for another. `daal4py` was not aware of `sklearnex` specifics, common logger was just stored in `daal4py` namespace.

I see what do you mean. So we used to have it, but it causes several problems. That is why this impl just inherited daal4py one functionality and just updates two methods, that should be stored on sklearnex side, since it is specific.