[testing, bug] include sklearn fallback for normal non-invertible matrices in preview linearRegression
intel/scikit-learn-intelex pull request #1528
Opened 2023-10-06 06:38 UTC by icfaust

# Description
Daal contains several methods for linear regression: https://github.com/oneapi-src/oneDAL/blob/master/cpp/daal/include/algorithms/linear_regression/linear_regression_training_types.h#L58 . oneDAL uses daal for CPU, but only has the norm_eq method available: https://github.com/oneapi-src/oneDAL/blob/master/cpp/oneapi/dal/algo/linear_regression/parameters/cpu/train_parameters.cpp#L42. Daal4py linear regression includes a fallback for non-invertible normal matrices: https://github.com/intel/scikit-learn-intelex/blob/master/daal4py/sklearn/linear_model/_linear.py#L61
sklearnex.preview.linearRegression does not have this fallback, meaning it cannot handle norm_eq non-invertible matrices.
Ideally additional work should be done on the oneDAL side to include the QRdense method, and then expose it to sklearnex. This can be considered a stopgap bugfix.

This causes unit test failures for sklearn preview in public Nightly:
inspection/tests/test_partial_dependence.py::test_partial_dependence_easy_target[1-est0]
inspection/tests/test_partial_dependence.py::test_partial_dependence_easy_target[1-est1]
inspection/tests/test_partial_dependence.py::test_partial_dependence_easy_target[1-est2]
inspection/tests/test_partial_dependence.py::test_partial_dependence_easy_target[1-est3]
inspection/tests/test_partial_dependence.py::test_partial_dependence_easy_target[2-est0]
inspection/tests/test_partial_dependence.py::test_partial_dependence_easy_target[2-est1]
inspection/tests/test_partial_dependence.py::test_partial_dependence_easy_target[2-est2]
inspection/tests/test_partial_dependence.py::test_partial_dependence_easy_target[2-est3]
Changes proposed in this pull request:
- Include a try catch for a Runtime error, fallback to sklearn due to non-invertibility.

2023-10-06 06:41 UTC, icfaust commented
/intelci: run

2023-10-06 06:41 UTC, icfaust commented
/azp run Nightly

2023-10-06 08:19 UTC, KulikovNikita commented on sklearnex/preview/linear_model/linear.py
> +                super().fit(X, y)
Looks weird. Yes, it will fix the problem for now. Unfortunately we don't quite understand what is causing the problem on onedal side

2023-10-06 09:11 UTC, Alexsandruss requested changes

2023-10-06 09:11 UTC, Alexsandruss commented on sklearnex/preview/linear_model/linear.py
> +                super().fit(X, y)
No warning about fallback to stock implementation is provided.

2023-10-06 10:09 UTC, icfaust commented
/azp run Nightly

2023-10-06 10:20 UTC, icfaust commented
/intelci: run

2023-10-06 10:20 UTC, icfaust commented
/azp run Nightly

2023-10-06 10:33 UTC, icfaust commented
/intelci: run

2023-10-06 10:33 UTC, icfaust commented
/azp run Nightly

2023-10-06 12:07 UTC, Alexsandruss commented on sklearnex/preview/linear_model/linear.py
> +                logging.getlogger("sklearnex").info(
```suggestion
                logging.getLogger("sklearnex").info(
```

2023-10-06 12:10 UTC, icfaust commented
/intelci: run

2023-10-06 13:55 UTC, icfaust commented
/intelci: restart

2023-10-06 13:59 UTC, icfaust commented
manual rerun of private CI http://intel-ci.intel.com/ee644fea-91ee-f107-96d4-a4bf010d0e2e

2023-10-06 15:02 UTC, icfaust commented
Pre-commit failure is intermittent and unrelated to this PR, see manual rereun

2023-10-06 17:16 UTC, icfaust commented
![image](https://github.com/intel/scikit-learn-intelex/assets/4824475/77daa510-0395-419c-9fe0-189c25c5f81e)

2023-10-06 18:25 UTC, icfaust commented
/intelci: run

2023-10-06 18:25 UTC, icfaust commented
/azp run Nightly

2023-10-06 20:13 UTC, icfaust commented
![image](https://github.com/intel/scikit-learn-intelex/assets/4824475/26b662c8-231c-49e6-b390-8ebcf09f3d01)
The failed tests shown here are solved in #1507

2023-10-07 10:17 UTC, Alexsandruss approved these changes

2023-10-07 10:17 UTC, merged