Enable build on ARM(SVE)
intel/scikit-learn-intelex pull request #1771
Opened 2024-03-22 11:15 UTC by ajay-fuji

# Description
### Enable scikit-learn-intelex build on ARM(SVE) cpu -
Now since oneDAL officially support arm CPUs [PR-2614](https://github.com/oneapi-src/oneDAL/pull/2614), this PR will enable Scikit-learn-intelex build on arm CPUs. 
# Changes proposed in this PR :
  - Remove hardcoded architecture directory (`arch_dir`) name (intel64). Implemented run time selection of `arch_dir` based on backend CPU.

2024-03-22 11:44 UTC, napetrov commented
/intelci: run

2024-03-22 11:52 UTC, icfaust reviewed
Update to generalize beyond just arm

2024-03-22 11:52 UTC, icfaust commented on daal4py/__init__.py
> +        arch_dir = plt_arch
```suggestion
    arch_dir = platform.machine()
    plt_dict = {"x86_64":"intel64", "aarch64":"arm"}
    arch_dir = plt_dict[arch_dir] if arch_dir in plt_dict else arch_dir
```

2024-03-22 11:52 UTC, icfaust commented on onedal/__init__.py
> +
```suggestion
    arch_dir = platform.machine()
    plt_dict = {"x86_64":"intel64", "aarch64":"arm"}
    arch_dir = plt_dict[arch_dir] if arch_dir in plt_dict else arch_dir
```
More general for possible future expansion.

2024-03-22 11:52 UTC, icfaust commented on scripts/build_backend.py
> +
```suggestion
    arch_dir = plt.machine()
    plt_dict = {"x86_64":"intel64", "aarch64":"arm"}
    arch_dir = plt_dict[arch_dir] if arch_dir in plt_dict else arch_dir
```

2024-03-22 11:52 UTC, icfaust commented on setup.py
> +
```suggestion
arch_dir = plt.machine()
plt_dict = {"x86_64":"intel64", "aarch64":"arm"}
arch_dir = plt_dict[arch_dir] if arch_dir in plt_dict else arch_dir
```

2024-03-22 11:52 UTC, icfaust commented on tests/run_examples.py
> +
```suggestion
arch_dir = plt.machine()
plt_dict = {"x86_64":"intel64", "aarch64":"arm"}
arch_dir = plt_dict[arch_dir] if arch_dir in plt_dict else arch_dir
```

2024-03-25 17:17 UTC, ajay-fuji commented
@icfaust are there any recommended changes to be made on this PR?

2024-03-26 21:43 UTC, icfaust commented
> @icfaust are there any recommended changes to be made on this PR?

Let me get someone else more experienced to give this PR a look, but it looks fine to me.

2024-03-28 14:59 UTC, ethanglaser commented
/intelci: run

2024-03-28 15:04 UTC, napetrov approved these changes

2024-03-28 18:39 UTC, ethanglaser requested changes
Please add "AMD64": "intel64" to the plt_dirs

2024-03-29 18:49 UTC, ethanglaser approved these changes

2024-03-29 18:49 UTC, merged