Add sparse data support for LogisticRegression
intel/scikit-learn-intelex pull request #1985
Opened 2024-08-02 08:54 UTC by avolkov-intel

### Description

This PR introduce changes to support sparse data for Logistic Regression training and inference on GPU (for CPU sparse data will not be supported yet). Also a few tests were implemented

Checklist to comply with before moving PR from draft:

**PR completeness and readability**

- [ ] I have reviewed my changes thoroughly before submitting this pull request.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation to reflect the changes or created a separate PR with update and provided its number in the description, if necessary.
- [ ] Git commit message contains an appropriate signed-off-by string _(see [CONTRIBUTING.md](https://github.com/intel/scikit-learn-intelex/blob/main/CONTRIBUTING.md#pull-requests) for details)_.
- [ ] I have added a respective label(s) to PR if I have a permission for that.  
- [ ] I have resolved any merge conflicts that might occur with the base branch.

**Testing**

- [ ] The unit tests pass successfully.
- [ ] I have run it locally and tested the changes extensively.

**Performance**

- [ ] I have measured performance for affected algorithms using [scikit-learn_bench](https://github.com/IntelPython/scikit-learn_bench) and provided at least summary table with measured data, if performance change is expected.
- [ ] I have provided justification why performance has changed or why changes are not expected.

2024-08-02 12:26 UTC, avolkov-intel commented
/intelci: run

2024-08-17 14:47 UTC, Vika-F reviewed
The changes look good to me. Even versioning is in place.
For some reason I cannot see the results of pre-commit testing, but if everything is Ok there, then LGTM.

2024-08-21 10:18 UTC, avolkov-intel commented
/intelci: run

2024-08-21 16:53 UTC, avolkov-intel commented
/intelci: run

2024-08-21 19:32 UTC, Alexsandruss requested changes

2024-08-21 19:32 UTC, Alexsandruss commented on onedal/linear_model/logistic_regression.cpp
> +        #endif // defined(ONEDAL_VERSION) && ONEDAL_VERSION >=20240700
Wrong formatting
```suggestion
#if ONEDAL_VERSION >= 20240700
        ONEDAL_PARAM_DISPATCH_VALUE(method, "sparse", ops, Float, method::sparse);
#endif
```

2024-08-21 19:32 UTC, Alexsandruss commented on onedal/linear_model/tests/test_logistic_regression.py
> +if daal_check_version((2024, "P", 600)):
This condition mentions 2024.6.0 version while `onedal` and onther places - 2024.7.0. Are you sure you set correct versions?

2024-08-21 22:08 UTC, avolkov-intel commented
/intelci: run

2024-08-22 09:52 UTC, Alexsandruss approved these changes

2024-08-22 09:52 UTC, merged

2024-08-22 16:43 UTC, avolkov-intel commented
@Mergifyio copy rls/2024.7.0-rls