[bug] fix n_jobs support coverage to indirectly-supported oneDAL methods
intel/scikit-learn-intelex pull request #2054
Opened 2024-09-16 10:20 UTC by icfaust

### Description

This adds a trace coverage check for all callable methods for all estimators to see if n_jobs is being properly set for oneDAL offload circumstances.  Seems that I missed a lot of them in "score" method support.  This PR is an extension on #2048 using the same testing fixtures.

---

Checklist to comply with before moving PR from draft:

**PR completeness and readability**

- [ ] I have reviewed my changes thoroughly before submitting this pull request.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation to reflect the changes or created a separate PR with update and provided its number in the description, if necessary.
- [ ] Git commit message contains an appropriate signed-off-by string _(see [CONTRIBUTING.md](https://github.com/intel/scikit-learn-intelex/blob/main/CONTRIBUTING.md#pull-requests) for details)_.
- [ ] I have added a respective label(s) to PR if I have a permission for that.  
- [ ] I have resolved any merge conflicts that might occur with the base branch.

**Testing**

- [ ] The unit tests pass successfully.
- [ ] I have run it locally and tested the changes extensively.

**Performance**

- [ ] I have measured performance for affected algorithms using [scikit-learn_bench](https://github.com/IntelPython/scikit-learn_bench) and provided at least summary table with measured data, if performance change is expected.
- [ ] I have provided justification why performance has changed or why changes are not expected.

2024-09-17 13:58 UTC, icfaust commented
/intelci: run

2024-09-17 22:21 UTC, icfaust commented
/intelci: run

2024-09-18 08:03 UTC, icfaust commented
/intelci: run

2024-09-18 09:22 UTC, icfaust commented
/intelci: run

2024-09-20 07:02 UTC, icfaust commented
/intelci: run

2024-09-20 19:37 UTC, icfaust commented
/intelci: run

2024-09-20 19:43 UTC, icfaust commented
/intelci: run

2024-09-24 14:22 UTC, samir-nasibli approved these changes
Thank you @icfaust 
I think checking estimators design by the rule is good, but again disputable in case should they be in the package it self or just in the repo.

2024-09-24 14:22 UTC, samir-nasibli commented on sklearnex/tests/test_common.py
> +    design_pattern(estimator_trace, estimator, method)
👍 I just love this initiative

2024-09-24 19:35 UTC, Alexsandruss requested changes

2024-09-24 19:35 UTC, Alexsandruss commented on daal4py/sklearn/_n_jobs_support.py
>              set_n_threads(old_n_threads)
What is the purpose of try-finally block? Is it to guarantee reset to `old_n_threads`? What will happen if `method` throws some error? I guess there will be no traceback

2024-09-25 12:48 UTC, icfaust commented
/intelci: run

2024-09-25 15:18 UTC, Alexsandruss approved these changes
Assuming intelci will finally start and pass.

2024-09-26 05:23 UTC, merged