TEST: clear a few warnings in model builder tests
intel/scikit-learn-intelex pull request #2064
Opened 2024-09-23 13:45 UTC by david-cortes-intel

### Description

This PR clears a few warnings that are observed when executing unit tests that involve building and converting models from XGBoost and LightGBM.

---

Checklist to comply with before moving PR from draft:

**PR completeness and readability**

- [x] I have reviewed my changes thoroughly before submitting this pull request.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation to reflect the changes or created a separate PR with update and provided its number in the description, if necessary.
- [x] Git commit message contains an appropriate signed-off-by string _(see [CONTRIBUTING.md](https://github.com/intel/scikit-learn-intelex/blob/main/CONTRIBUTING.md#pull-requests) for details)_.
- [x] I have added a respective label(s) to PR if I have a permission for that.  
- [x] I have resolved any merge conflicts that might occur with the base branch.

**Testing**

- [x] The unit tests pass successfully.
- [x] I have run it locally and tested the changes extensively.

**Performance**

- [ ] I have measured performance for affected algorithms using [scikit-learn_bench](https://github.com/IntelPython/scikit-learn_bench) and provided at least summary table with measured data, if performance change is expected.
- [ ] I have provided justification why performance has changed or why changes are not expected.

2024-09-23 13:55 UTC, Alexsandruss requested changes

2024-09-23 13:55 UTC, Alexsandruss commented on tests/test_model_builders.py
> +    def getConversionWarningIsExpected(self):
Use snake case.

2024-09-23 13:55 UTC, Alexsandruss commented on tests/test_model_builders.py
> +    def conditionalAssertWarns(self, warning):
Same here.

2024-09-23 13:55 UTC, Alexsandruss commented on tests/test_model_builders.py
>      def setUpClass(cls, base_score=0.5, n_classes=2, objective="binary:logistic"):
Same here.

2024-09-23 13:59 UTC, david-cortes-intel commented on tests/test_model_builders.py
> +    def getConversionWarningIsExpected(self):
Changed to snake case.

2024-09-25 14:36 UTC, Alexsandruss commented
@razdoburdin, pending on your review.

2024-09-25 14:42 UTC, razdoburdin commented on tests/test_model_builders.py
> +            num_boost_round=1,
why do you prefer setting `num_boost_round` to `n_estimators`?

2024-09-25 14:46 UTC, razdoburdin approved these changes
looks ok

2024-09-25 14:47 UTC, merged