Add information about daal4py in install.md file for sklearnex
intel/scikit-learn-intelex pull request #941
Opened 2022-01-11 20:22 UTC by Pahandrovich

2022-01-12 06:51 UTC, agorshk approved these changes

2022-01-12 07:28 UTC, KalyanovD approved these changes

2022-01-12 08:11 UTC, outoftardis approved these changes

2022-01-12 09:59 UTC, outoftardis requested changes
could you please also update the same info in docs: https://github.com/intel/scikit-learn-intelex/blob/master/doc/sources/installation.rst#build-from-sources

also note that the prerequisites there mention python version < 3.10, so I guess the same should be said here

2022-01-14 10:58 UTC, outoftardis approved these changes

2022-01-14 11:20 UTC, merged