Fix incorrect value in RF
intel/scikit-learn-intelex pull request #951
Opened 2022-01-20 20:38 UTC by lordoz234

Fixed incorrect value in plot_tree in Random Forest

2022-01-20 21:09 UTC, lordoz234 commented
/intelci: run

2022-01-21 11:31 UTC, Alexsandruss requested changes
Look at Segmentation Fault in CircleCI

2022-01-21 13:26 UTC, lordoz234 commented
/intelci: run

2022-01-21 14:53 UTC, agorshk commented on src/tree_visitor.h
> +            value_ar[id*1*class_count + desc.label] += desc.nNodeSampleCount;
Minor, as I see we don't have to multiply by 1

2022-01-24 11:21 UTC, Alexsandruss approved these changes

2022-01-25 17:36 UTC, merged